function init(self)
	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("touch") and action.pressed then
		-- print("touched")
		if gui.pick_node(gui.get_node("button"), action.x, action.y) then
			msg.post("main:/go#main_script", "load_selection")
		end
	end
end

function final(self)
	-- Release input focus when the game object is destroyed or removed
	msg.post(".", "release_input_focus")
end